//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Koszyk.cpp
//  @ Date : 30.03.2026
//  @ Author : 
//
//


#include "Koszyk.h"
#include "Pozycja.h"

#include <iostream>

Koszyk::Koszyk(int id) {
    this->idSesji = id;
}
Koszyk::~Koszyk() {
    for (Pozycja* pozycja: pozycje) {
        delete pozycja;
    }
}

void Koszyk::dodajPrzedmiot(Pozycja* pozycja) {
    pozycje.push_back(pozycja);
    std::cout << "Dodano do koszyka\n";
}

bool Koszyk::usunPrzedmiot(Pozycja* pozycja) {
    int el = -1;
    for (int i = 0; i < pozycje.size(); i++) {
        if (pozycje[i] == pozycja) {
            el = i;
            break;
        }
    }
    if (el != -1) {
        pozycje.erase(pozycje.begin() + el);
        std::cout << "Usunieto z koszyka\n";
    }
    else
        std::cout << "Nie udalo sie usunac\n";
}

void Koszyk::wyswietlPodsumowanie() {
    std::cout<< "----------PODSUMOWANIE----------\n";
    for (int i = 0; i < pozycje.size(); i++) {
        std::cout << pozycje[i]->getNazwa() << '\n';
        std::cout<< pozycje[i]->getCenaUSD() << "USD\n";
        std::cout << pozycje[i]->getCenaPLN() << "PLN\n\n";
    }
    std::cout<< "--------------------------------\n";
}

