//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Koszyk.h
//  @ Date : 30.03.2026
//  @ Author : 
//
//


#if !defined(_KOSZYK_H)
#define _KOSZYK_H

#include "Pozycja.h"
#include <vector>

class Koszyk {
public:
	Koszyk(int id);
	~Koszyk();
	void dodajPrzedmiot(Pozycja* pozycja);
	bool usunPrzedmiot(Pozycja* pozycja);
	void wyswietlPodsumowanie();
private:
	string idSesji;
	vector<Pozycja*> pozycje;
};

#endif  //_KOSZYK_H
