//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pozycja.h
//  @ Date : 30.03.2026
//  @ Author : 
//
//


#if !defined(_POZYCJA_H)
#define _POZYCJA_H

#include <string>

#include "PrzelicznikCeny.h"

using namespace std;

class Pozycja {
public:
	float getCenaUSD();
	float getCenaPLN();
	string getNazwa();
	Pozycja(string nazwa, float cenaUSD, int id, PrzelicznikCeny* przelicznik);
private:
	string nazwa;
	float cenaUSD;
	int id;
	PrzelicznikCeny* przelicznik;
};

#endif  //_POZYCJA_H
