//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pozycja.cpp
//  @ Date : 30.03.2026
//  @ Author : 
//
//


#include "Pozycja.h"

float Pozycja::getCenaUSD() {
    return cenaUSD;
}

float Pozycja::getCenaPLN() {
    return przelicznik->przelicz(cenaUSD);
}

string Pozycja::getNazwa() {
    return nazwa;
}

Pozycja::Pozycja(string nazwa, float cenaUSD, int id, PrzelicznikCeny* przelicznik) {
    this->nazwa = nazwa;
    this->cenaUSD = cenaUSD;
    this->id = id;
    this->przelicznik = przelicznik;
}

