//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PrzelicznikCeny.h
//  @ Date : 30.03.2026
//  @ Author : 
//
//


#if !defined(_PRZELICZNIKCENY_H)
#define _PRZELICZNIKCENY_H


class PrzelicznikCeny {
public:
	float przelicz(float kwota);
	float getKurs();
	PrzelicznikCeny(float kursUSD);
private:
	float kursUSD;
};

#endif  //_PRZELICZNIKCENY_H
