//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PrzelicznikCeny.cpp
//  @ Date : 30.03.2026
//  @ Author : 
//
//


#include "PrzelicznikCeny.h"

float PrzelicznikCeny::przelicz(float kwota) {
    return kwota*kursUSD;
}

float PrzelicznikCeny::getKurs() {
    return kursUSD;
}

PrzelicznikCeny::PrzelicznikCeny(float kursUSD) {
    this->kursUSD = kursUSD;
}
